<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro" >
    <!-- 1.属性定义 -->
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="radius" value="0.03" />
    <!-- 1.属性调用 -->
    <myUsePropertyxxx name="${PI}" />
    <myUsePropertyxxx name="${radius}" />
    <!-- 1.算数运算 -->
    <myUsePropertyxxx result="${PI / 2}" />
    <myUsePropertyxxx result="${radius * 2}" />

</robot>